// Auth Types
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const RESET_SUCCESSFUL = 'RESET_SUCCESSFUL';
export const EMAIL_RESET_SUCCESSFUL = 'EMAIL_RESET_SUCCESSFUL';
export const RESET_FAILED = 'RESET_FAILED';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// Profile Types
export const USER_FOLLOWED = 'USER_FOLLOWED';
export const USER_FOLLOWED_FAILED = 'USER_FOLLOWED_FAILED';
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const CURRENT_PROFILE_LOADED = 'CURRENT_PROFILE_LOADED';
export const CURRENT_PROFILE_FAILED = 'CURRENT_PROFILE_FAILED';
export const PROFILE_LOADED_FAILED = 'PROFILE_LOADED_FAILED';
export const USER_FOLLOWING = 'USER_FOLLOWING';
export const USER_FOLLOWING_FAILED = 'USER_FOLLOWING_FAILED';
export const PROFILE_CREATED = 'PROFILE_CREATED';
export const USERNAME_LOADED = 'USERNAME_LOADED';
export const USERNAME_FAILED = 'USERNAME_FAILED';
export const PROFILE_CREATION_FAILED = 'PROFILE_CREATION_FAILED';

// Link types;
export const GET_NEW_LINK = 'GET_NEW_LINK';
export const GET_NEW_LINK_FAILED = 'GET_NEW_LINK_FAILED';

// Errors types
export const GET_ERRORS = 'GET_ERRORS';